name: Build AyOS Release APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Recreate Clean Android Structure
        run: |
          rm -rf android
          flutter create --platforms=android --org com.victors.ayos --project-name ayos .

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyOS-PS3-Launcher
          path: build/app/outputs/flutter-apk/app-release.apk